const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('Building Toggle Tables plugin...');

// Banner for the output file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE
if you want to view the source, please visit the github repository of this plugin
*/
`;

try {
    // Compile TypeScript to JavaScript
    console.log('Compiling TypeScript...');
    execSync('npx tsc main.ts --outDir . --target ES2018 --module CommonJS --moduleResolution node --esModuleInterop --allowSyntheticDefaultImports --skipLibCheck --noEmitOnError', { stdio: 'inherit' });
    
    // Read the compiled JavaScript
    const compiledJs = fs.readFileSync('main.js', 'utf8');
    
    // Create the final output with banner
    const finalOutput = banner + '\n' + compiledJs;
    
    // Write the final output
    fs.writeFileSync('main.js', finalOutput);
    
    console.log('Build completed successfully!');
    console.log('Output file: main.js');
    
} catch (error) {
    console.error('Build failed:', error.message);
    process.exit(1);
} 